---
default: true

commands-show-output: false
first-line-h1:
  front_matter_title: ""  # Ensure a H1 title exists even with a front matter
heading-style:
  style: atx
hr-style:
  style: "---"
line-length: false
no-trailing-punctuation:
  punctuation: ".,;:。，；：！？"  # Note: '!' and '?' are allowed
single-title:
  front_matter_title: ""  # Disabled if there's a front matter
ul-indent:
  indent: 2
ul-style:
  style: dash
no-inline-html: false
