version: '3'

services:

  kong:
    image: kong:3.0-ubuntu
    environment:
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/plugin-development/kong.yml
      - KONG_PLUGINS=bundled,${NAME}
      - KONG_MYPLUGIN_SOMEDATA={"foo":"bar","baz":"cux"}
      - KONG_VAULT_DATA={"foo":"bar","baz":"this string comes from kong vault"}
    volumes:
      - plugin-development:/plugin-development
    user: "0:0"
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /usr/local/lib/luarocks/rocks-5.1/kong-plugin-${NAME}/${VERSION}-1/
        ln -s /plugin-development/kong-plugin-${NAME}-${VERSION}-1.rockspec /usr/local/lib/luarocks/rocks-5.1/kong-plugin-${NAME}/${VERSION}-1/kong-plugin-${NAME}-${VERSION}-1.rockspec
        ln -s /plugin-development/kong/plugins/${NAME} /usr/local/share/lua/5.1/kong/plugins/${NAME}
        /docker-entrypoint.sh kong start --vv
    ports:
      - "8000:8000"
      - "8001:8001"

volumes:
  plugin-development:
    driver: local
    driver_opts:
       type: none
       o: bind
       device: ${PWD}/

networks:
  default:
    name: kong-plugin-development
    driver: bridge