---
_format_version: "1.1"

services:
- name: httpbin
  url: https://httpbin.org/anything

routes:
- hosts: []
  methods: []
  name: httpbin
  paths:
  - /
  preserve_host: false
  regex_priority: 1
  service: httpbin
  strip_path: false
  # plugins:
  # - name: my-plugin
  #   config:
  #     my_number: 44
  #     my_header: X-Foo-Bar
  #     my_string: "hello world"
